### ISSUE TITLE
PlayFair cipher (requested by #1)

### ISSUE THREAD

**Issue by vivekashok1221** [KuruvillaJacob02/Encryptions_Methods#4]
Hello 👋,
I would like to submit an implementation of Play Fair cipher as requested by issue #1.

Kindly assign this issue to me so that I can start working on it.

**Comment by KuruvillaJacob02** [comment]
Sure go ahead, thank you for your contribution

**Comment by KuruvillaJacob02** [comment]
This issue has been resolved
