### ISSUE TITLE
Add a book cipher

### ISSUE THREAD

**Issue by ScottVinay** [KuruvillaJacob02/Encryptions_Methods#8]
Hi, I would like to add a [running-key book cipher](https://en.wikipedia.org/wiki/Running_key_cipher) based on a public-domain text.

**Comment by ScottVinay** [comment]
Question for @KuruvillaJacob02 or others, should our function use default libraries only, or can we use numpy?

**Comment by KuruvillaJacob02** [comment]
> Question for @KuruvillaJacob02 or others, should our function use default libraries only, or can we use numpy?

@ScottVinay I'd prefer if default libraries are used for making the functions

**Comment by ScottVinay** [comment]
Sure thing

**Comment by KuruvillaJacob02** [comment]
Once again thank you for your contribution, I will now close this issue
