### ISSUE TITLE
Want to add Reverse Cipher 

### ISSUE THREAD

**Issue by hacky1997** [KuruvillaJacob02/Encryptions_Methods#9]
I want to add reverse cipher using python. Could you please assign me?

**Comment by KuruvillaJacob02** [comment]
Sure go ahead, I'll assign this issue to you

**Comment by KuruvillaJacob02** [comment]
I declined the PR, because it wasn't satisfactory, take a look at the other files so that you get an idea

**Comment by KuruvillaJacob02** [comment]
I saw your newly updated PR, and all the problems were resolved, thank you for the contribution
